import = [
	"~/.config/alacritty/themes/themes/rose-pine-moon.toml"
]

[window]
padding = { x = 16, y = 16 }

[font]
size = 20
normal		= { family = "ProggyCleanSZ Nerd Font Mono", style = "Regular" }
bold		= { family = "ProggyCleanSZ Nerd Font Mono", style = "Bold" }
italic		= { family = "ProggyCleanSZ Nerd Font Mono", style = "Italic" }
bold_italic	= { family = "ProggyCleanSZ Nerd Font Mono", style = "Bold Italic" }
